### ISSUE TITLE
[TODO]: write tests for the rest of the CRUD operations for users

### ISSUE THREAD

**Issue by emoral435** [emoral435/swole-goal#13]
**Summary**
Create tests for all CRUD operations defined in our users.sql.go file

**Task**
- [ ] Write tests for our DeleteUser fn to see if it works properly
- [ ] Write tests for our UpdateUser fn to see if it works properly
- [ ] Write tests for our GetUser fn to see if it works properly

# Related
